### ISSUE TITLE
데이터 레이블링 문의

### ISSUE THREAD

**Issue by cosao** [songys/Chatbot_data#3]
안녕하세요

일전에 메일로도 문의를 드렸는데

Custom data로 모델 학습 진행을 위해 Custom dataset을 제작하여 활용하고자합니다.

동일한 구성으로 임의로 데이터 셋을 제작해보았습니다.

하지만 
![image](https://github.com/songys/Chatbot_data/assets/53820991/58058a15-7600-411c-8061-e9d1702eee85)
이와 같은 에러가 발생하였습니다.

![image](https://github.com/songys/Chatbot_data/assets/53820991/a6f2be36-6bae-4c37-81c1-dd1f35af9175)
미리보기와 같이 작성을 진행했는데 무슨 차이가 있을까요?

**Comment by songys** [comment]
보캡 id mapping에 문제가 없는지 확인해 보시겠어요? 

예컨대 내가 정의한 보캡 사이즈는 1000개인데,
tokenizing 결과의 배열에서
[0, 315, 125152, 332]
이런식으로 1000개보다 큰 숫자가 나온 듯합니다.

**Comment by cosao** [comment]
답변 감사합니다!! 덕분에 해결되었습니다.
